<?php
define("SITE_URL","http://localhost/filelister");
define("IMAGE_URL","http://localhost/CampusDiary/filelister/");
define("UPLOAD_PATH","http://localhost/CampusDiary/filelister/");
define("DB_NAME","filelister");
define("DB_HOST","localhost");
define("DB_USER","foste2cj_admin");
define("DB_PASS","ybAA-(P=G}9P");
define("DB_PREFIX","filelister_");
define("ACCESS_KEY","ibnu2s049976vv7");
define("SECRET_KEY","de7phidghimpmhq");
?>
